# Preparing Your Data for ML

##  Learning Outcomes

After this video, you'll be able to:

<ul>
    <li>Load and inspect raw data using Pandas</li>
    <li>Clean missing and inconsistent data</li>
    <li>Prepare features for machine learning models</li>
</ul>

## Environment Setup

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Load our dataset
df = pd.read_csv('insightlysoft_dataset_uncleaned.csv')
df.head()

,account_id,monthly_login_freq,num_support_tickets,contract_length_months,avg_product_usage_hours,num_users,nps_score,has_admin_activity,last_activity_days_ago,avg_session_length,feature_adoption_score,customer_satisfaction_score,city,gender,churned
0,A0001,21.0,0,6,28.16,58,NaN,0,5,1.51,89.98,8.42,Chicago,Female,0
1,A0002,13.0,0,6,18.70,33,6.0,1,20,1.33,11.82,1.33,new york,female,1
2,A0003,23.0,1,6,32.73,61,32.0,0,2,0.48,31.07,6.60,Austin,Female,0
3,A0004,NaN,1,6,9.25,4,NaN,0,34,2.04,77.84,NaN,Chicago,male,1
4,A0005,NaN,5,24,29.08,99,NaN,0,4,1.92,54.32,NaN,Austin,female,0

## Data Inspection

In [2]:
# Let's look at our data
print("Dataset Shape:", df.shape)
print("\nFirst few rows:")
df.head()

Dataset Shape: (1000, 15)

First few rows:

,account_id,monthly_login_freq,num_support_tickets,contract_length_months,avg_product_usage_hours,num_users,nps_score,has_admin_activity,last_activity_days_ago,avg_session_length,feature_adoption_score,customer_satisfaction_score,city,gender,churned
0,A0001,21.0,0,6,28.16,58,NaN,0,5,1.51,89.98,8.42,Chicago,Female,0
1,A0002,13.0,0,6,18.70,33,6.0,1,20,1.33,11.82,1.33,new york,female,1
2,A0003,23.0,1,6,32.73,61,32.0,0,2,0.48,31.07,6.60,Austin,Female,0
3,A0004,NaN,1,6,9.25,4,NaN,0,34,2.04,77.84,NaN,Chicago,male,1
4,A0005,NaN,5,24,29.08,99,NaN,0,4,1.92,54.32,NaN,Austin,female,0

In [3]:
# Check for missing values
missing_values = df.isnull().sum()
print("\nMissing Values:\n", missing_values)

Missing Values:
 account_id                      0
monthly_login_freq             52
num_support_tickets             0
contract_length_months          0
avg_product_usage_hours         0
num_users                       0
nps_score                      52
has_admin_activity              0
last_activity_days_ago          0
avg_session_length              0
feature_adoption_score          0
customer_satisfaction_score    52
city                            0
gender                          0
churned                         0
dtype: int64

## Train-Test Split

In [4]:
# Separate features and target
X = df.drop('churned', axis=1)
y = df['churned']

# Create train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# Create training_df to continue with data preparation
training_df = X_train.copy()
training_df['churned'] = y_train
training_df.head()

,account_id,monthly_login_freq,num_support_tickets,contract_length_months,avg_product_usage_hours,num_users,nps_score,has_admin_activity,last_activity_days_ago,avg_session_length,feature_adoption_score,customer_satisfaction_score,city,gender,churned
29,A0030,19.0,2,24,32.14,49,26.0,1,7,1.25,76.36,5.74,New York,Male,1
535,A0536,24.0,0,6,19.53,53,54.0,0,5,2.44,99.74,3.09,New York,Female,0
695,A0696,23.0,3,12,20.21,11,38.0,1,14,1.57,5.22,6.83,San Francisco,Male,1
557,A0558,14.0,3,6,25.74,39,-1.0,0,15,0.97,66.17,8.47,Austin,Male,1
836,A0837,21.0,1,12,38.64,32,31.0,1,0,2.28,94.30,7.94,Austin,Male,0

## Data Standardization

In [5]:
# Standardize text columns
training_df['city'] = training_df['city'].str.strip().str.title()
training_df['gender'] = training_df['gender'].str.strip().str.lower()

# Check unique values
print("Unique cities:", training_df['city'].unique())
print("Unique genders:", training_df['gender'].unique())

Unique cities: ['New York' 'San Francisco' 'Austin' 'Chicago']
Unique genders: ['male' 'female']

## Handling Missing Values

In [6]:
# Handle numeric missing values
numeric_cols = training_df.select_dtypes(include=['float64', 'int64']).columns
for col in numeric_cols:
    if training_df[col].isnull().any():
        median_value = training_df[col].median()
        training_df[col].fillna(median_value, inplace=True)
training_df.head()

,account_id,monthly_login_freq,num_support_tickets,contract_length_months,avg_product_usage_hours,num_users,nps_score,has_admin_activity,last_activity_days_ago,avg_session_length,feature_adoption_score,customer_satisfaction_score,city,gender,churned
29,A0030,19.0,2,24,32.14,49,26.0,1,7,1.25,76.36,5.74,New York,male,1
535,A0536,24.0,0,6,19.53,53,54.0,0,5,2.44,99.74,3.09,New York,female,0
695,A0696,23.0,3,12,20.21,11,38.0,1,14,1.57,5.22,6.83,San Francisco,male,1
557,A0558,14.0,3,6,25.74,39,-1.0,0,15,0.97,66.17,8.47,Austin,male,1
836,A0837,21.0,1,12,38.64,32,31.0,1,0,2.28,94.30,7.94,Austin,male,0

In [7]:
# Handle categorical missing values
categorical_cols = training_df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    if training_df[col].isnull().any():
        mode_value = training_df[col].mode()[0]
        training_df[col].fillna(mode_value, inplace=True)
training_df.head()

,account_id,monthly_login_freq,num_support_tickets,contract_length_months,avg_product_usage_hours,num_users,nps_score,has_admin_activity,last_activity_days_ago,avg_session_length,feature_adoption_score,customer_satisfaction_score,city,gender,churned
29,A0030,19.0,2,24,32.14,49,26.0,1,7,1.25,76.36,5.74,New York,male,1
535,A0536,24.0,0,6,19.53,53,54.0,0,5,2.44,99.74,3.09,New York,female,0
695,A0696,23.0,3,12,20.21,11,38.0,1,14,1.57,5.22,6.83,San Francisco,male,1
557,A0558,14.0,3,6,25.74,39,-1.0,0,15,0.97,66.17,8.47,Austin,male,1
836,A0837,21.0,1,12,38.64,32,31.0,1,0,2.28,94.30,7.94,Austin,male,0

## Feature Preparation

In [8]:
# One-hot encode categorical variables
training_df = pd.get_dummies(training_df, columns=['city', 'gender'])

# Scale numerical features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
training_df[numeric_cols] = scaler.fit_transform(training_df[numeric_cols])
training_df.head()

,account_id,monthly_login_freq,num_support_tickets,contract_length_months,avg_product_usage_hours,num_users,nps_score,has_admin_activity,last_activity_days_ago,avg_session_length,feature_adoption_score,customer_satisfaction_score,churned,city_Austin,city_Chicago,city_New York,city_San Francisco,gender_female,gender_male
29,A0030,-0.200159,-0.214483,1.748683,0.263512,-0.090614,-0.128334,1.227940,-0.496422,-0.512701,0.858159,0.264370,1.151339,False,False,True,False,False,True
535,A0536,0.842336,-1.609492,-0.830813,-0.985454,0.051526,0.835676,-0.814372,-0.632919,1.778162,1.664899,-0.684091,-0.868554,False,False,True,False,True,False
695,A0696,0.633837,0.483022,0.029019,-0.918103,-1.440941,0.284813,1.227940,-0.018683,0.103329,-1.596567,0.654492,1.151339,False,False,False,True,False,True
557,A0558,-1.242654,0.483022,-0.830813,-0.370380,-0.445963,-1.057915,-0.814372,0.049565,-1.051727,0.506547,1.241464,1.151339,True,False,False,False,False,True
836,A0837,0.216839,-0.911988,0.029019,0.907310,-0.694708,0.043811,1.227940,-0.974161,1.470147,1.477189,1.051772,-0.868554,True,False,False,False,False,True

## Recap


In this video, we covered:

- Inspecting and cleaning raw data using Pandas 

- Implementing strategic missing value handling 

- Standardizing and transforming features 

- Preparing data splits for model training